Create header and headline
Lornakaboro/my-portfolio pull request #1
Opened 2022-08-19 13:35 UTC by Lornakaboro

This is a portfolio that is aimed at showcasing my accomplishments  ,skills , educational and work backgrounds.
I created  index.html, style.css ,READ.me files.
I also added a background and social media images from Figma.

### Getting Started

To get a local copy up and running follow these simple example steps.

### Prerequisites

- Git installed in desktop
- Code editor of your choice i.e; Visual Studio Code
- Browser of your choice i.e; Mozilla Firefox
- Terminal of your choice i.e; Git Bash

### Setup

To get a local copy up and running follow these simple example steps.
- use the git clone command with this [link](git@github.com:Lornakaboro/my-portfolio.git)
- cd into my-portfolio
- Switch branch using this command `git checkout create-header-and-headline`
- Open index.html in your browser
- You will be able to see a template with my name, a brief description and social media handles

2022-08-19 16:50 UTC, mahbubul14 requested changes
Hi @Lornakaboro ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Github flow used properly.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "fix bug".` [For more details.](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

- [ ] Please use [CSS Media Queries](https://www.w3schools.com/css/css3_mediaqueries.asp) for your mobile version. It is not currently optimized for the mobile version.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-08-19 16:50 UTC, mahbubul14 commented on index.html
> +    </div>
- [ ] Instead of a `div` tag it should be wrapped in a `header` tag. Kindly work on it. :+1:

2022-08-19 16:50 UTC, mahbubul14 commented on index.html
> +      <h3 class="logo">My Logo</h3>
- [ ] The logo ("My logo") on the left should be in `a` tag. :+1:

2022-08-19 16:50 UTC, mahbubul14 commented on index.html
> +    </div>
- [ ] This section should be wrapped in a `section` tag. :+1:

2022-08-19 16:50 UTC, mahbubul14 commented on index.html
> +      </div>
- [ ] The list of icons should be in a ul tag to group them, and li per icon; each icon has a link (a tag). :+1:

2022-08-19 16:50 UTC, mahbubul14 commented on style.css
> +}
- [ ] The content should be aligned with flexbox. This gives us a lot of options to align all our elements, plus, it's responsive. Kindly work on it. :+1:

2022-08-20 07:12 UTC, emmiiorji approved these changes
Hi @Lornakaboro, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![goodjob-slowclap](https://user-images.githubusercontent.com/20554583/185733433-d4d94238-c2b0-4100-b70c-a55837e7cf34.gif)


## Good Highlights ✅

- Requested changes have been implemented
- Good commit messages
- Linter checks are passing

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:

- organizing your images into a folder so as to cluttering the root folder.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 07:12 UTC, emmiiorji commented on README.md
> +
_[Optional]_ I recommend that you replace "Author1" with your name because you'll agree that it suggests so.

2022-08-20 13:14 UTC, merged