Create contact form
Lornakaboro/my-portfolio pull request #3
Opened 2022-08-24 14:33 UTC by Lornakaboro

This is a portfolio that is aimed at showcasing my accomplishments  ,skills , educational, work backgrounds and contact form.
I added a contact form section. You can view a preview of it in the screenshot below:-
![image](https://user-images.githubusercontent.com/106239921/186443885-8cc6f211-e6aa-4920-bf37-7c78b39ee5b2.png)

### Getting Started

To get a local copy up and running follow these simple example steps.

### Prerequisites

- Git installed in desktop
- Code editor of your choice i.e; Visual Studio Code
- Browser of your choice i.e; Mozilla Firefox
- Terminal of your choice i.e; Git Bash

### Setup

To get a local copy up and running follow these simple example steps.
- use the git clone command with this [link](git@github.com:Lornakaboro/my-portfolio.git)
- cd into my-portfolio
- Switch branch using this command `git checkout create-contact-form`
- Open index.html in your browser
- You will be able to see a template with a contact form

2022-08-26 21:21 UTC, Ismailco requested changes
### Hi Team, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 21:21 UTC, Ismailco commented on index.html
> +        <form action="https://formspree.io/f/mpznwdqe" class="contact-form-content">
- [ ] You should stick to the design templates in Figma as much as possible, this includes the font, colors, images, and spacing (margin/padding), kindly add the proper background image to the form so it looks like the provided design

2022-08-27 17:09 UTC, muneebulrehman requested changes
Hi @Lornakaboro , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 17:09 UTC, muneebulrehman commented on index.html
> +        <form action="https://formspree.io/f/mpznwdqe" class="contact-form-content">
Hey @Lornakaboro, as asked by the previous reviewer, you must adhere to the Figma template of your choosing. Kindly update your contact section as per the provided design including background images if any, margins, padding, font color, font family, font size, etc.
| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/33268927/187040593-6bace917-bc37-457a-917c-b2863ba011a3.png) | ![image](https://user-images.githubusercontent.com/33268927/187040611-c4f44c76-3bca-491c-8909-1897fb54f2e7.png) |

2022-08-27 17:09 UTC, muneebulrehman commented on index.html
> +        <form action="https://formspree.io/f/mpznwdqe" class="contact-form-content">
Kindly add a `POST` method to your form so as to post the information to the formspree service.

2022-08-27 17:09 UTC, muneebulrehman commented on index.html
> +              placeholder ="enter username" value="Alexandra Loremipsum" required="required" maxlength="30" >
- Optional.
Kindly remove the `value` attribute because it just ruins the user experience because the user first has to delete the value which is prefilled and then enter their details.

2022-08-27 18:12 UTC, Lornakaboro commented
@Ismailco @muneebulrehman , I have modified my media queries to show the background image from a max width of 480px and lower.

2022-08-27 18:23 UTC, Lornakaboro commented
> @Ismailco @muneebulrehman , I have modified my media queries to show the background image from a max width of 480px and lower.

I have submitted

2022-08-27 18:25 UTC, mgmediaweb commented on index.html
> +        <form action="https://formspree.io/f/mpznwdqe" class="contact-form-content">
Good job following the advice of the previous reviewer

2022-08-27 18:26 UTC, mgmediaweb commented on index.html
> +        <form action="https://formspree.io/f/mpznwdqe" class="contact-form-content">
Good job following the advice of the previous reviewer

2022-08-27 18:26 UTC, mgmediaweb commented on index.html
> +              placeholder ="enter username" value="Alexandra Loremipsum" required="required" maxlength="30" >
Good job following the advice of the previous reviewer

2022-08-27 18:29 UTC, mgmediaweb approved these changes
Hi @Lornakaboro, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approved1](https://user-images.githubusercontent.com/41912912/187043462-760a3ac1-e107-493a-9cf7-3489401c2960.gif)

## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 18:43 UTC, merged